#cloudbuild.yaml
steps:
# build the container image
- name: 'docker/compose:1.19.0'
  args: ['up', '-d']
# Push the container image to Container Registry
- name: 'docker/compose:1.19.0'
  args: ['push', 'gcr.io/work-env/cogs-container']
